version: '3.3'
services:
  db:
    container_name: mssql
    build: 
      context: ./mssql_init/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_DB=database
      - MSSQL_USER=user
      - MSSQL_PASSWORD=vkKRP4PLBT1@2a
  


