version: '3.3'
services:
  db_prod:
    container_name: mssql
    build: 
      context: ./mssql_init/
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_DB=database
      - MSSQL_USER=user
      - MSSQL_PASSWORD=vkKRP4PLBT1@2a
    
  api:
    container_name: rest-api
    build: .
    restart: always
    command: sh entrypoint.sh
    environment: 
      NODE_ENV: production
    ports:
      - "8080:8080"
    depends_on: 
      - db_prod
    volumes:
      - ./logs:/docker_api/logs